CREATE TABLE `/*TABLE_PREFIX*/t_news` (
  `pk_i_id` INT(10) NOT NULL AUTO_INCREMENT, 
  `dt_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
  `message` MEDIUMTEXT NULL DEFAULT NULL,
  `i_priority` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_i_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
